server:
  port: 8081

spring:
  application:
      name: metrics-producer
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

topic:
  metrics-event: metrics-event


management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
        application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true


# Path: metrics-producer/src/main/resources/application.yml