apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: psql:5432
    database: metrics
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"