{
 "title": "Spring boot metrics from PostgreSQL",
 "time": { "from": "2024-03-24T05:21:04.777Z", "to": "2024-03-24T05:25:31.965Z" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT me.value as time_value, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'process.uptime' \nORDER BY me.timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Files opened ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT me.value as time_value, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'process.files.open' \nORDER BY me.timestamp DESC\nLIMIT 1"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT me.value as memory_used, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'jvm.memory.used' \nORDER BY me.timestamp DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT me.value as cpu_usage, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'system.cpu.usage' \nORDER BY me.timestamp DESC\nLIMIT 1000\n"
    }
   ]
  },
  {
   "title": "Threads Live and Daemon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT me.value as thread_live, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'jvm.threads.live' \nORDER BY me.timestamp DESC\nLIMIT 1000"
    },
    {
     "rawSql": "SELECT me.value as thread_daemon, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'jvm.threads.daemon' \nORDER BY me.timestamp DESC\nLIMIT 1000\n"
    }
   ]
  },
  {
   "title": "JVM Memory commited (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT me.value as memory_commited, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'jvm.memory.committed' \nORDER BY me.timestamp DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "JVM cpu usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT me.value as jvm_cpu_usage, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'process.cpu.usage' \nORDER BY me.timestamp DESC\nLIMIT 1000\n"
    }
   ]
  },
  {
   "title": "GC memory allocated (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT me.value as gc_memory_allocated, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'jvm.gc.memory.allocated' \nORDER BY me.timestamp DESC\nLIMIT 1000"
    }
   ]
  }
 ]
}