{
 "title": "Spring boot metrics from PostgreSQL",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT me.value as time_value, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'process.uptime' \nORDER BY me.timestamp DESC\nLIMIT 1"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT me.value as memory_used, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'jvm.memory.used' \nORDER BY me.timestamp DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT me.value as cpu_usage, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'system.cpu.usage' \nORDER BY me.timestamp DESC\nLIMIT 1000\n"
    }
   ]
  },
  {
   "title": "Threads Live and Daemon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT me.value as thread_live, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'jvm.threads.live' \nORDER BY me.timestamp DESC\nLIMIT 1000"
    },
    {
     "rawSql": "SELECT me.value as thread_daemon, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'jvm.threads.daemon' \nORDER BY me.timestamp DESC\nLIMIT 1000\n"
    }
   ]
  },
  { "title": "HTTP server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Tomcat session created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT me.value as tomcat_session_created, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'tomcat.sessions.created' \nORDER BY me.timestamp DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Tomcat active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT me.value as active_sessions, me.timestamp as time, me.name \nFROM meter_entity me \nWHERE me.name = 'tomcat.sessions.active.current' \nORDER BY me.timestamp DESC\nLIMIT 1000"
    }
   ]
  }
 ]
}